/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdsd.simplepalladio.AllocationViewTypeRuntimeModule;
import org.xtext.mdsd.simplepalladio.AllocationViewTypeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AllocationViewTypeIdeSetup extends AllocationViewTypeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AllocationViewTypeRuntimeModule(), new AllocationViewTypeIdeModule()));
	}
	
}
