/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RepositoryViewTypeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RepositoryViewTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.RepositoryViewType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRepositoryViewTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRepositoryElementsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRepositoryElementsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRepositoryElementsAbstractRepositoryElementParserRuleCall_4_0 = (RuleCall)cRepositoryElementsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRepositoryElementsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRepositoryElementsAbstractRepositoryElementParserRuleCall_5_1_0 = (RuleCall)cRepositoryElementsAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RepositoryViewType SystemIndependentViewPoint::RepositoryViewType:
		//	'RepositoryViewType'
		//	'{'
		//	'repositoryElements' '{' repositoryElements+=AbstractRepositoryElement (","
		//	repositoryElements+=AbstractRepositoryElement)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RepositoryViewType'
		//'{'
		//'repositoryElements' '{' repositoryElements+=AbstractRepositoryElement (","
		//repositoryElements+=AbstractRepositoryElement)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RepositoryViewType'
		public Keyword getRepositoryViewTypeKeyword_0() { return cRepositoryViewTypeKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'repositoryElements'
		public Keyword getRepositoryElementsKeyword_2() { return cRepositoryElementsKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//repositoryElements+=AbstractRepositoryElement
		public Assignment getRepositoryElementsAssignment_4() { return cRepositoryElementsAssignment_4; }
		
		//AbstractRepositoryElement
		public RuleCall getRepositoryElementsAbstractRepositoryElementParserRuleCall_4_0() { return cRepositoryElementsAbstractRepositoryElementParserRuleCall_4_0; }
		
		//("," repositoryElements+=AbstractRepositoryElement)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//repositoryElements+=AbstractRepositoryElement
		public Assignment getRepositoryElementsAssignment_5_1() { return cRepositoryElementsAssignment_5_1; }
		
		//AbstractRepositoryElement
		public RuleCall getRepositoryElementsAbstractRepositoryElementParserRuleCall_5_1_0() { return cRepositoryElementsAbstractRepositoryElementParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AbstractRepositoryElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.AbstractRepositoryElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInterfaceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCompositeComponentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSignatureParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cComponentParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//AbstractRepositoryElement SystemIndependentViewPoint::AbstractRepositoryElement:
		//	Interface | CompositeComponent | Signature | Component;
		@Override public ParserRule getRule() { return rule; }
		
		//Interface | CompositeComponent | Signature | Component
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Interface
		public RuleCall getInterfaceParserRuleCall_0() { return cInterfaceParserRuleCall_0; }
		
		//CompositeComponent
		public RuleCall getCompositeComponentParserRuleCall_1() { return cCompositeComponentParserRuleCall_1; }
		
		//Signature
		public RuleCall getSignatureParserRuleCall_2() { return cSignatureParserRuleCall_2; }
		
		//Component
		public RuleCall getComponentParserRuleCall_3() { return cComponentParserRuleCall_3; }
	}
	public class InterfaceCommunicatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.InterfaceCommunicator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCompositeComponentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComponentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//InterfaceCommunicator SystemIndependentViewPoint::InterfaceCommunicator:
		//	CompositeComponent | Component;
		@Override public ParserRule getRule() { return rule; }
		
		//CompositeComponent | Component
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CompositeComponent
		public RuleCall getCompositeComponentParserRuleCall_0() { return cCompositeComponentParserRuleCall_0; }
		
		//Component
		public RuleCall getComponentParserRuleCall_1() { return cComponentParserRuleCall_1; }
	}
	public class AbstractComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.AbstractComponent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCompositeComponentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComponentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractComponent SystemIndependentViewPoint::AbstractComponent:
		//	CompositeComponent | Component;
		@Override public ParserRule getRule() { return rule; }
		
		//CompositeComponent | Component
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CompositeComponent
		public RuleCall getCompositeComponentParserRuleCall_0() { return cCompositeComponentParserRuleCall_0; }
		
		//Component
		public RuleCall getComponentParserRuleCall_1() { return cComponentParserRuleCall_1; }
	}
	public class BehaviorElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.BehaviorElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInternalActionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExternalCallParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLoopParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBranchParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//BehaviorElement SystemIndependentViewPoint::BehaviorElement:
		//	InternalAction | ExternalCall | Loop | Branch;
		@Override public ParserRule getRule() { return rule; }
		
		//InternalAction | ExternalCall | Loop | Branch
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//InternalAction
		public RuleCall getInternalActionParserRuleCall_0() { return cInternalActionParserRuleCall_0; }
		
		//ExternalCall
		public RuleCall getExternalCallParserRuleCall_1() { return cExternalCallParserRuleCall_1; }
		
		//Loop
		public RuleCall getLoopParserRuleCall_2() { return cLoopParserRuleCall_2; }
		
		//Branch
		public RuleCall getBranchParserRuleCall_3() { return cBranchParserRuleCall_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class InterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Interface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInterfaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSignaturesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSignaturesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cSignaturesSignatureCrossReference_5_0 = (CrossReference)cSignaturesAssignment_5.eContents().get(0);
		private final RuleCall cSignaturesSignatureEStringParserRuleCall_5_0_1 = (RuleCall)cSignaturesSignatureCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSignaturesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cSignaturesSignatureCrossReference_6_1_0 = (CrossReference)cSignaturesAssignment_6_1.eContents().get(0);
		private final RuleCall cSignaturesSignatureEStringParserRuleCall_6_1_0_1 = (RuleCall)cSignaturesSignatureCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Interface SystemIndependentViewPoint::Interface:
		//	'Interface'
		//	name=EString
		//	'{'
		//	'signatures' '(' signatures+=[SystemIndependentViewPoint::Signature|EString] (","
		//	signatures+=[SystemIndependentViewPoint::Signature|EString])* ')'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Interface'
		//name=EString
		//'{'
		//'signatures' '(' signatures+=[SystemIndependentViewPoint::Signature|EString] (","
		//signatures+=[SystemIndependentViewPoint::Signature|EString])* ')'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Interface'
		public Keyword getInterfaceKeyword_0() { return cInterfaceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'signatures'
		public Keyword getSignaturesKeyword_3() { return cSignaturesKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//signatures+=[SystemIndependentViewPoint::Signature|EString]
		public Assignment getSignaturesAssignment_5() { return cSignaturesAssignment_5; }
		
		//[SystemIndependentViewPoint::Signature|EString]
		public CrossReference getSignaturesSignatureCrossReference_5_0() { return cSignaturesSignatureCrossReference_5_0; }
		
		//EString
		public RuleCall getSignaturesSignatureEStringParserRuleCall_5_0_1() { return cSignaturesSignatureEStringParserRuleCall_5_0_1; }
		
		//("," signatures+=[SystemIndependentViewPoint::Signature|EString])*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//signatures+=[SystemIndependentViewPoint::Signature|EString]
		public Assignment getSignaturesAssignment_6_1() { return cSignaturesAssignment_6_1; }
		
		//[SystemIndependentViewPoint::Signature|EString]
		public CrossReference getSignaturesSignatureCrossReference_6_1_0() { return cSignaturesSignatureCrossReference_6_1_0; }
		
		//EString
		public RuleCall getSignaturesSignatureEStringParserRuleCall_6_1_0_1() { return cSignaturesSignatureEStringParserRuleCall_6_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CompositeComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.CompositeComponent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRequiredInterfacesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRequiredInterfacesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cRequiredInterfacesInterfaceCrossReference_3_2_0 = (CrossReference)cRequiredInterfacesAssignment_3_2.eContents().get(0);
		private final RuleCall cRequiredInterfacesInterfaceEStringParserRuleCall_3_2_0_1 = (RuleCall)cRequiredInterfacesInterfaceCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRequiredInterfacesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cRequiredInterfacesInterfaceCrossReference_3_3_1_0 = (CrossReference)cRequiredInterfacesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cRequiredInterfacesInterfaceEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cRequiredInterfacesInterfaceCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cProvidedInterfacesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cProvidedInterfacesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cProvidedInterfacesInterfaceCrossReference_6_0 = (CrossReference)cProvidedInterfacesAssignment_6.eContents().get(0);
		private final RuleCall cProvidedInterfacesInterfaceEStringParserRuleCall_6_0_1 = (RuleCall)cProvidedInterfacesInterfaceCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cProvidedInterfacesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cProvidedInterfacesInterfaceCrossReference_7_1_0 = (CrossReference)cProvidedInterfacesAssignment_7_1.eContents().get(0);
		private final RuleCall cProvidedInterfacesInterfaceEStringParserRuleCall_7_1_0_1 = (RuleCall)cProvidedInterfacesInterfaceCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cSystemKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cSystemAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cSystemSystemCrossReference_10_0 = (CrossReference)cSystemAssignment_10.eContents().get(0);
		private final RuleCall cSystemSystemEStringParserRuleCall_10_0_1 = (RuleCall)cSystemSystemCrossReference_10_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//CompositeComponent SystemIndependentViewPoint::CompositeComponent:
		//	'CompositeComponent'
		//	name=EString
		//	'{' ('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//	requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
		//	'providedInterfaces' '(' providedInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//	providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')'
		//	'system' system=[AssemblyViewPoint::System|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'CompositeComponent'
		//name=EString
		//'{' ('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
		//'providedInterfaces' '(' providedInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')'
		//'system' system=[AssemblyViewPoint::System|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'CompositeComponent'
		public Keyword getCompositeComponentKeyword_0() { return cCompositeComponentKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'requiredInterfaces'
		public Keyword getRequiredInterfacesKeyword_3_0() { return cRequiredInterfacesKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getRequiredInterfacesAssignment_3_2() { return cRequiredInterfacesAssignment_3_2; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getRequiredInterfacesInterfaceCrossReference_3_2_0() { return cRequiredInterfacesInterfaceCrossReference_3_2_0; }
		
		//EString
		public RuleCall getRequiredInterfacesInterfaceEStringParserRuleCall_3_2_0_1() { return cRequiredInterfacesInterfaceEStringParserRuleCall_3_2_0_1; }
		
		//("," requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getRequiredInterfacesAssignment_3_3_1() { return cRequiredInterfacesAssignment_3_3_1; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getRequiredInterfacesInterfaceCrossReference_3_3_1_0() { return cRequiredInterfacesInterfaceCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getRequiredInterfacesInterfaceEStringParserRuleCall_3_3_1_0_1() { return cRequiredInterfacesInterfaceEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//'providedInterfaces'
		public Keyword getProvidedInterfacesKeyword_4() { return cProvidedInterfacesKeyword_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//providedInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getProvidedInterfacesAssignment_6() { return cProvidedInterfacesAssignment_6; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getProvidedInterfacesInterfaceCrossReference_6_0() { return cProvidedInterfacesInterfaceCrossReference_6_0; }
		
		//EString
		public RuleCall getProvidedInterfacesInterfaceEStringParserRuleCall_6_0_1() { return cProvidedInterfacesInterfaceEStringParserRuleCall_6_0_1; }
		
		//("," providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//providedInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getProvidedInterfacesAssignment_7_1() { return cProvidedInterfacesAssignment_7_1; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getProvidedInterfacesInterfaceCrossReference_7_1_0() { return cProvidedInterfacesInterfaceCrossReference_7_1_0; }
		
		//EString
		public RuleCall getProvidedInterfacesInterfaceEStringParserRuleCall_7_1_0_1() { return cProvidedInterfacesInterfaceEStringParserRuleCall_7_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'system'
		public Keyword getSystemKeyword_9() { return cSystemKeyword_9; }
		
		//system=[AssemblyViewPoint::System|EString]
		public Assignment getSystemAssignment_10() { return cSystemAssignment_10; }
		
		//[AssemblyViewPoint::System|EString]
		public CrossReference getSystemSystemCrossReference_10_0() { return cSystemSystemCrossReference_10_0; }
		
		//EString
		public RuleCall getSystemSystemEStringParserRuleCall_10_0_1() { return cSystemSystemEStringParserRuleCall_10_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class SignatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Signature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSignatureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cReturnValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cReturnValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cReturnValueTypeEnumRuleCall_4_0 = (RuleCall)cReturnValueAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cParametersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cParametersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_5_2_0 = (RuleCall)cParametersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cParametersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_5_3_1_0 = (RuleCall)cParametersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Signature SystemIndependentViewPoint::Signature:
		//	'Signature'
		//	name=EString
		//	'{'
		//	'returnValue' returnValue=Type ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Signature'
		//name=EString
		//'{'
		//'returnValue' returnValue=Type ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Signature'
		public Keyword getSignatureKeyword_0() { return cSignatureKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'returnValue'
		public Keyword getReturnValueKeyword_3() { return cReturnValueKeyword_3; }
		
		//returnValue=Type
		public Assignment getReturnValueAssignment_4() { return cReturnValueAssignment_4; }
		
		//Type
		public RuleCall getReturnValueTypeEnumRuleCall_4_0() { return cReturnValueTypeEnumRuleCall_4_0; }
		
		//('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'parameters'
		public Keyword getParametersKeyword_5_0() { return cParametersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_5_2() { return cParametersAssignment_5_2; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_5_2_0() { return cParametersParameterParserRuleCall_5_2_0; }
		
		//("," parameters+=Parameter)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//parameters+=Parameter
		public Assignment getParametersAssignment_5_3_1() { return cParametersAssignment_5_3_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_5_3_1_0() { return cParametersParameterParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRequiredInterfacesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRequiredInterfacesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cRequiredInterfacesInterfaceCrossReference_3_2_0 = (CrossReference)cRequiredInterfacesAssignment_3_2.eContents().get(0);
		private final RuleCall cRequiredInterfacesInterfaceEStringParserRuleCall_3_2_0_1 = (RuleCall)cRequiredInterfacesInterfaceCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRequiredInterfacesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cRequiredInterfacesInterfaceCrossReference_3_3_1_0 = (CrossReference)cRequiredInterfacesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cRequiredInterfacesInterfaceEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cRequiredInterfacesInterfaceCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cProvidedInterfacesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cProvidedInterfacesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cProvidedInterfacesInterfaceCrossReference_6_0 = (CrossReference)cProvidedInterfacesAssignment_6.eContents().get(0);
		private final RuleCall cProvidedInterfacesInterfaceEStringParserRuleCall_6_0_1 = (RuleCall)cProvidedInterfacesInterfaceCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cProvidedInterfacesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cProvidedInterfacesInterfaceCrossReference_7_1_0 = (CrossReference)cProvidedInterfacesAssignment_7_1.eContents().get(0);
		private final RuleCall cProvidedInterfacesInterfaceEStringParserRuleCall_7_1_0_1 = (RuleCall)cProvidedInterfacesInterfaceCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cServicesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cServicesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cServicesServiceParserRuleCall_11_0 = (RuleCall)cServicesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cServicesAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cServicesServiceParserRuleCall_12_1_0 = (RuleCall)cServicesAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Component SystemIndependentViewPoint::Component:
		//	'Component'
		//	name=EString
		//	'{' ('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//	requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
		//	'providedInterfaces' '(' providedInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//	providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')'
		//	'services' '{' services+=Service ("," services+=Service)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Component'
		//name=EString
		//'{' ('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
		//'providedInterfaces' '(' providedInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')'
		//'services' '{' services+=Service ("," services+=Service)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Component'
		public Keyword getComponentKeyword_0() { return cComponentKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'requiredInterfaces'
		public Keyword getRequiredInterfacesKeyword_3_0() { return cRequiredInterfacesKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getRequiredInterfacesAssignment_3_2() { return cRequiredInterfacesAssignment_3_2; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getRequiredInterfacesInterfaceCrossReference_3_2_0() { return cRequiredInterfacesInterfaceCrossReference_3_2_0; }
		
		//EString
		public RuleCall getRequiredInterfacesInterfaceEStringParserRuleCall_3_2_0_1() { return cRequiredInterfacesInterfaceEStringParserRuleCall_3_2_0_1; }
		
		//("," requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getRequiredInterfacesAssignment_3_3_1() { return cRequiredInterfacesAssignment_3_3_1; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getRequiredInterfacesInterfaceCrossReference_3_3_1_0() { return cRequiredInterfacesInterfaceCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getRequiredInterfacesInterfaceEStringParserRuleCall_3_3_1_0_1() { return cRequiredInterfacesInterfaceEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//'providedInterfaces'
		public Keyword getProvidedInterfacesKeyword_4() { return cProvidedInterfacesKeyword_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//providedInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getProvidedInterfacesAssignment_6() { return cProvidedInterfacesAssignment_6; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getProvidedInterfacesInterfaceCrossReference_6_0() { return cProvidedInterfacesInterfaceCrossReference_6_0; }
		
		//EString
		public RuleCall getProvidedInterfacesInterfaceEStringParserRuleCall_6_0_1() { return cProvidedInterfacesInterfaceEStringParserRuleCall_6_0_1; }
		
		//("," providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//providedInterfaces+=[SystemIndependentViewPoint::Interface|EString]
		public Assignment getProvidedInterfacesAssignment_7_1() { return cProvidedInterfacesAssignment_7_1; }
		
		//[SystemIndependentViewPoint::Interface|EString]
		public CrossReference getProvidedInterfacesInterfaceCrossReference_7_1_0() { return cProvidedInterfacesInterfaceCrossReference_7_1_0; }
		
		//EString
		public RuleCall getProvidedInterfacesInterfaceEStringParserRuleCall_7_1_0_1() { return cProvidedInterfacesInterfaceEStringParserRuleCall_7_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'services'
		public Keyword getServicesKeyword_9() { return cServicesKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//services+=Service
		public Assignment getServicesAssignment_11() { return cServicesAssignment_11; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_11_0() { return cServicesServiceParserRuleCall_11_0; }
		
		//("," services+=Service)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//services+=Service
		public Assignment getServicesAssignment_12_1() { return cServicesAssignment_12_1; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_12_1_0() { return cServicesServiceParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParameterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeTypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parameter SystemIndependentViewPoint::Parameter:
		//	'Parameter'
		//	name=EString
		//	'{'
		//	'type' type=Type
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Parameter'
		//name=EString
		//'{'
		//'type' type=Type
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Parameter'
		public Keyword getParameterKeyword_0() { return cParameterKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=Type
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_4_0() { return cTypeTypeEnumRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Service");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSignatureKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSignatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSignatureSignatureCrossReference_3_0 = (CrossReference)cSignatureAssignment_3.eContents().get(0);
		private final RuleCall cSignatureSignatureEStringParserRuleCall_3_0_1 = (RuleCall)cSignatureSignatureCrossReference_3_0.eContents().get(1);
		private final Keyword cBehaviourDescriptionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBehaviourDescriptionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBehaviourDescriptionBehaviourDescriptionParserRuleCall_5_0 = (RuleCall)cBehaviourDescriptionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Service SystemIndependentViewPoint::Service:
		//	'Service'
		//	'{'
		//	'signature' signature=[SystemIndependentViewPoint::Signature|EString]
		//	'behaviourDescription' behaviourDescription=BehaviourDescription
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Service'
		//'{'
		//'signature' signature=[SystemIndependentViewPoint::Signature|EString]
		//'behaviourDescription' behaviourDescription=BehaviourDescription
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Service'
		public Keyword getServiceKeyword_0() { return cServiceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'signature'
		public Keyword getSignatureKeyword_2() { return cSignatureKeyword_2; }
		
		//signature=[SystemIndependentViewPoint::Signature|EString]
		public Assignment getSignatureAssignment_3() { return cSignatureAssignment_3; }
		
		//[SystemIndependentViewPoint::Signature|EString]
		public CrossReference getSignatureSignatureCrossReference_3_0() { return cSignatureSignatureCrossReference_3_0; }
		
		//EString
		public RuleCall getSignatureSignatureEStringParserRuleCall_3_0_1() { return cSignatureSignatureEStringParserRuleCall_3_0_1; }
		
		//'behaviourDescription'
		public Keyword getBehaviourDescriptionKeyword_4() { return cBehaviourDescriptionKeyword_4; }
		
		//behaviourDescription=BehaviourDescription
		public Assignment getBehaviourDescriptionAssignment_5() { return cBehaviourDescriptionAssignment_5; }
		
		//BehaviourDescription
		public RuleCall getBehaviourDescriptionBehaviourDescriptionParserRuleCall_5_0() { return cBehaviourDescriptionBehaviourDescriptionParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class BehaviourDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.BehaviourDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBehaviourDescriptionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBehaviourDescriptionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cBehaviorElementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cBehaviorElementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cBehaviorElementsBehaviorElementParserRuleCall_3_2_0 = (RuleCall)cBehaviorElementsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cBehaviorElementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cBehaviorElementsBehaviorElementParserRuleCall_3_3_1_0 = (RuleCall)cBehaviorElementsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//BehaviourDescription SystemIndependentViewPoint::BehaviourDescription:
		//	{SystemIndependentViewPoint::BehaviourDescription}
		//	'BehaviourDescription'
		//	'{' ('behaviorElements' '{' behaviorElements+=BehaviorElement ("," behaviorElements+=BehaviorElement)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SystemIndependentViewPoint::BehaviourDescription}
		//'BehaviourDescription'
		//'{' ('behaviorElements' '{' behaviorElements+=BehaviorElement ("," behaviorElements+=BehaviorElement)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SystemIndependentViewPoint::BehaviourDescription}
		public Action getBehaviourDescriptionAction_0() { return cBehaviourDescriptionAction_0; }
		
		//'BehaviourDescription'
		public Keyword getBehaviourDescriptionKeyword_1() { return cBehaviourDescriptionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('behaviorElements' '{' behaviorElements+=BehaviorElement ("," behaviorElements+=BehaviorElement)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'behaviorElements'
		public Keyword getBehaviorElementsKeyword_3_0() { return cBehaviorElementsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//behaviorElements+=BehaviorElement
		public Assignment getBehaviorElementsAssignment_3_2() { return cBehaviorElementsAssignment_3_2; }
		
		//BehaviorElement
		public RuleCall getBehaviorElementsBehaviorElementParserRuleCall_3_2_0() { return cBehaviorElementsBehaviorElementParserRuleCall_3_2_0; }
		
		//("," behaviorElements+=BehaviorElement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//behaviorElements+=BehaviorElement
		public Assignment getBehaviorElementsAssignment_3_3_1() { return cBehaviorElementsAssignment_3_3_1; }
		
		//BehaviorElement
		public RuleCall getBehaviorElementsBehaviorElementParserRuleCall_3_3_1_0() { return cBehaviorElementsBehaviorElementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class InternalActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.InternalAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInternalActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInternalActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//InternalAction SystemIndependentViewPoint::InternalAction:
		//	{SystemIndependentViewPoint::InternalAction}
		//	'InternalAction';
		@Override public ParserRule getRule() { return rule; }
		
		//{SystemIndependentViewPoint::InternalAction}
		//'InternalAction'
		public Group getGroup() { return cGroup; }
		
		//{SystemIndependentViewPoint::InternalAction}
		public Action getInternalActionAction_0() { return cInternalActionAction_0; }
		
		//'InternalAction'
		public Keyword getInternalActionKeyword_1() { return cInternalActionKeyword_1; }
	}
	public class ExternalCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.ExternalCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExternalCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSignatureKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSignatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSignatureSignatureCrossReference_3_0 = (CrossReference)cSignatureAssignment_3.eContents().get(0);
		private final RuleCall cSignatureSignatureEStringParserRuleCall_3_0_1 = (RuleCall)cSignatureSignatureCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ExternalCall SystemIndependentViewPoint::ExternalCall:
		//	'ExternalCall'
		//	'{'
		//	'signature' signature=[SystemIndependentViewPoint::Signature|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ExternalCall'
		//'{'
		//'signature' signature=[SystemIndependentViewPoint::Signature|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ExternalCall'
		public Keyword getExternalCallKeyword_0() { return cExternalCallKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'signature'
		public Keyword getSignatureKeyword_2() { return cSignatureKeyword_2; }
		
		//signature=[SystemIndependentViewPoint::Signature|EString]
		public Assignment getSignatureAssignment_3() { return cSignatureAssignment_3; }
		
		//[SystemIndependentViewPoint::Signature|EString]
		public CrossReference getSignatureSignatureCrossReference_3_0() { return cSignatureSignatureCrossReference_3_0; }
		
		//EString
		public RuleCall getSignatureSignatureEStringParserRuleCall_3_0_1() { return cSignatureSignatureEStringParserRuleCall_3_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLoopAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLoopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cBehaviorElementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cBehaviorElementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cBehaviorElementsBehaviorElementCrossReference_3_2_0 = (CrossReference)cBehaviorElementsAssignment_3_2.eContents().get(0);
		private final RuleCall cBehaviorElementsBehaviorElementEStringParserRuleCall_3_2_0_1 = (RuleCall)cBehaviorElementsBehaviorElementCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cBehaviorElementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cBehaviorElementsBehaviorElementCrossReference_3_3_1_0 = (CrossReference)cBehaviorElementsAssignment_3_3_1.eContents().get(0);
		private final RuleCall cBehaviorElementsBehaviorElementEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cBehaviorElementsBehaviorElementCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Loop SystemIndependentViewPoint::Loop:
		//	{SystemIndependentViewPoint::Loop}
		//	'Loop'
		//	'{' ('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
		//	behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SystemIndependentViewPoint::Loop}
		//'Loop'
		//'{' ('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SystemIndependentViewPoint::Loop}
		public Action getLoopAction_0() { return cLoopAction_0; }
		
		//'Loop'
		public Keyword getLoopKeyword_1() { return cLoopKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'behaviorElements'
		public Keyword getBehaviorElementsKeyword_3_0() { return cBehaviorElementsKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString]
		public Assignment getBehaviorElementsAssignment_3_2() { return cBehaviorElementsAssignment_3_2; }
		
		//[SystemIndependentViewPoint::BehaviorElement|EString]
		public CrossReference getBehaviorElementsBehaviorElementCrossReference_3_2_0() { return cBehaviorElementsBehaviorElementCrossReference_3_2_0; }
		
		//EString
		public RuleCall getBehaviorElementsBehaviorElementEStringParserRuleCall_3_2_0_1() { return cBehaviorElementsBehaviorElementEStringParserRuleCall_3_2_0_1; }
		
		//("," behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString]
		public Assignment getBehaviorElementsAssignment_3_3_1() { return cBehaviorElementsAssignment_3_3_1; }
		
		//[SystemIndependentViewPoint::BehaviorElement|EString]
		public CrossReference getBehaviorElementsBehaviorElementCrossReference_3_3_1_0() { return cBehaviorElementsBehaviorElementCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getBehaviorElementsBehaviorElementEStringParserRuleCall_3_3_1_0_1() { return cBehaviorElementsBehaviorElementEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BranchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Branch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBranchAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBranchKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cBehaviorElementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cBehaviorElementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cBehaviorElementsBehaviorElementCrossReference_3_2_0 = (CrossReference)cBehaviorElementsAssignment_3_2.eContents().get(0);
		private final RuleCall cBehaviorElementsBehaviorElementEStringParserRuleCall_3_2_0_1 = (RuleCall)cBehaviorElementsBehaviorElementCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cBehaviorElementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cBehaviorElementsBehaviorElementCrossReference_3_3_1_0 = (CrossReference)cBehaviorElementsAssignment_3_3_1.eContents().get(0);
		private final RuleCall cBehaviorElementsBehaviorElementEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cBehaviorElementsBehaviorElementCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Branch SystemIndependentViewPoint::Branch:
		//	{SystemIndependentViewPoint::Branch}
		//	'Branch'
		//	'{' ('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
		//	behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SystemIndependentViewPoint::Branch}
		//'Branch'
		//'{' ('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SystemIndependentViewPoint::Branch}
		public Action getBranchAction_0() { return cBranchAction_0; }
		
		//'Branch'
		public Keyword getBranchKeyword_1() { return cBranchKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'behaviorElements'
		public Keyword getBehaviorElementsKeyword_3_0() { return cBehaviorElementsKeyword_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }
		
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString]
		public Assignment getBehaviorElementsAssignment_3_2() { return cBehaviorElementsAssignment_3_2; }
		
		//[SystemIndependentViewPoint::BehaviorElement|EString]
		public CrossReference getBehaviorElementsBehaviorElementCrossReference_3_2_0() { return cBehaviorElementsBehaviorElementCrossReference_3_2_0; }
		
		//EString
		public RuleCall getBehaviorElementsBehaviorElementEStringParserRuleCall_3_2_0_1() { return cBehaviorElementsBehaviorElementEStringParserRuleCall_3_2_0_1; }
		
		//("," behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString]
		public Assignment getBehaviorElementsAssignment_3_3_1() { return cBehaviorElementsAssignment_3_3_1; }
		
		//[SystemIndependentViewPoint::BehaviorElement|EString]
		public CrossReference getBehaviorElementsBehaviorElementCrossReference_3_3_1_0() { return cBehaviorElementsBehaviorElementCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getBehaviorElementsBehaviorElementEStringParserRuleCall_3_3_1_0_1() { return cBehaviorElementsBehaviorElementEStringParserRuleCall_3_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class TypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mdsd.simplepalladio.RepositoryViewType.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVOIDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVOIDVOIDKeyword_0_0 = (Keyword)cVOIDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBOOLEANBOOLEANKeyword_1_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCHAREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCHARCHARKeyword_2_0 = (Keyword)cCHAREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDATEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDATEDATEKeyword_3_0 = (Keyword)cDATEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDOUBLEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDOUBLEDOUBLEKeyword_4_0 = (Keyword)cDOUBLEEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cFLOATEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cFLOATFLOATKeyword_5_0 = (Keyword)cFLOATEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cLISTEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cLISTLISTKeyword_6_0 = (Keyword)cLISTEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cINTEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cINTINTKeyword_7_0 = (Keyword)cINTEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cLONGEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cLONGLONGKeyword_8_0 = (Keyword)cLONGEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cMAPEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cMAPMAPKeyword_9_0 = (Keyword)cMAPEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cSTRINGSTRINGKeyword_10_0 = (Keyword)cSTRINGEnumLiteralDeclaration_10.eContents().get(0);
		
		//enum Type returns SystemIndependentViewPoint::Type:
		//	VOID | BOOLEAN | CHAR | DATE | DOUBLE | FLOAT | LIST | INT | LONG | MAP | STRING;
		public EnumRule getRule() { return rule; }
		
		//VOID | BOOLEAN | CHAR | DATE | DOUBLE | FLOAT | LIST | INT | LONG | MAP | STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VOID
		public EnumLiteralDeclaration getVOIDEnumLiteralDeclaration_0() { return cVOIDEnumLiteralDeclaration_0; }
		
		//'VOID'
		public Keyword getVOIDVOIDKeyword_0_0() { return cVOIDVOIDKeyword_0_0; }
		
		//BOOLEAN
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_1() { return cBOOLEANEnumLiteralDeclaration_1; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANBOOLEANKeyword_1_0() { return cBOOLEANBOOLEANKeyword_1_0; }
		
		//CHAR
		public EnumLiteralDeclaration getCHAREnumLiteralDeclaration_2() { return cCHAREnumLiteralDeclaration_2; }
		
		//'CHAR'
		public Keyword getCHARCHARKeyword_2_0() { return cCHARCHARKeyword_2_0; }
		
		//DATE
		public EnumLiteralDeclaration getDATEEnumLiteralDeclaration_3() { return cDATEEnumLiteralDeclaration_3; }
		
		//'DATE'
		public Keyword getDATEDATEKeyword_3_0() { return cDATEDATEKeyword_3_0; }
		
		//DOUBLE
		public EnumLiteralDeclaration getDOUBLEEnumLiteralDeclaration_4() { return cDOUBLEEnumLiteralDeclaration_4; }
		
		//'DOUBLE'
		public Keyword getDOUBLEDOUBLEKeyword_4_0() { return cDOUBLEDOUBLEKeyword_4_0; }
		
		//FLOAT
		public EnumLiteralDeclaration getFLOATEnumLiteralDeclaration_5() { return cFLOATEnumLiteralDeclaration_5; }
		
		//'FLOAT'
		public Keyword getFLOATFLOATKeyword_5_0() { return cFLOATFLOATKeyword_5_0; }
		
		//LIST
		public EnumLiteralDeclaration getLISTEnumLiteralDeclaration_6() { return cLISTEnumLiteralDeclaration_6; }
		
		//'LIST'
		public Keyword getLISTLISTKeyword_6_0() { return cLISTLISTKeyword_6_0; }
		
		//INT
		public EnumLiteralDeclaration getINTEnumLiteralDeclaration_7() { return cINTEnumLiteralDeclaration_7; }
		
		//'INT'
		public Keyword getINTINTKeyword_7_0() { return cINTINTKeyword_7_0; }
		
		//LONG
		public EnumLiteralDeclaration getLONGEnumLiteralDeclaration_8() { return cLONGEnumLiteralDeclaration_8; }
		
		//'LONG'
		public Keyword getLONGLONGKeyword_8_0() { return cLONGLONGKeyword_8_0; }
		
		//MAP
		public EnumLiteralDeclaration getMAPEnumLiteralDeclaration_9() { return cMAPEnumLiteralDeclaration_9; }
		
		//'MAP'
		public Keyword getMAPMAPKeyword_9_0() { return cMAPMAPKeyword_9_0; }
		
		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_10() { return cSTRINGEnumLiteralDeclaration_10; }
		
		//'STRING'
		public Keyword getSTRINGSTRINGKeyword_10_0() { return cSTRINGSTRINGKeyword_10_0; }
	}
	
	private final RepositoryViewTypeElements pRepositoryViewType;
	private final AbstractRepositoryElementElements pAbstractRepositoryElement;
	private final InterfaceCommunicatorElements pInterfaceCommunicator;
	private final AbstractComponentElements pAbstractComponent;
	private final BehaviorElementElements pBehaviorElement;
	private final EStringElements pEString;
	private final InterfaceElements pInterface;
	private final CompositeComponentElements pCompositeComponent;
	private final SignatureElements pSignature;
	private final ComponentElements pComponent;
	private final TypeElements eType;
	private final ParameterElements pParameter;
	private final ServiceElements pService;
	private final BehaviourDescriptionElements pBehaviourDescription;
	private final InternalActionElements pInternalAction;
	private final ExternalCallElements pExternalCall;
	private final LoopElements pLoop;
	private final BranchElements pBranch;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RepositoryViewTypeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRepositoryViewType = new RepositoryViewTypeElements();
		this.pAbstractRepositoryElement = new AbstractRepositoryElementElements();
		this.pInterfaceCommunicator = new InterfaceCommunicatorElements();
		this.pAbstractComponent = new AbstractComponentElements();
		this.pBehaviorElement = new BehaviorElementElements();
		this.pEString = new EStringElements();
		this.pInterface = new InterfaceElements();
		this.pCompositeComponent = new CompositeComponentElements();
		this.pSignature = new SignatureElements();
		this.pComponent = new ComponentElements();
		this.eType = new TypeElements();
		this.pParameter = new ParameterElements();
		this.pService = new ServiceElements();
		this.pBehaviourDescription = new BehaviourDescriptionElements();
		this.pInternalAction = new InternalActionElements();
		this.pExternalCall = new ExternalCallElements();
		this.pLoop = new LoopElements();
		this.pBranch = new BranchElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.mdsd.simplepalladio.RepositoryViewType".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RepositoryViewType SystemIndependentViewPoint::RepositoryViewType:
	//	'RepositoryViewType'
	//	'{'
	//	'repositoryElements' '{' repositoryElements+=AbstractRepositoryElement (","
	//	repositoryElements+=AbstractRepositoryElement)* '}'
	//	'}';
	public RepositoryViewTypeElements getRepositoryViewTypeAccess() {
		return pRepositoryViewType;
	}
	
	public ParserRule getRepositoryViewTypeRule() {
		return getRepositoryViewTypeAccess().getRule();
	}
	
	//AbstractRepositoryElement SystemIndependentViewPoint::AbstractRepositoryElement:
	//	Interface | CompositeComponent | Signature | Component;
	public AbstractRepositoryElementElements getAbstractRepositoryElementAccess() {
		return pAbstractRepositoryElement;
	}
	
	public ParserRule getAbstractRepositoryElementRule() {
		return getAbstractRepositoryElementAccess().getRule();
	}
	
	//InterfaceCommunicator SystemIndependentViewPoint::InterfaceCommunicator:
	//	CompositeComponent | Component;
	public InterfaceCommunicatorElements getInterfaceCommunicatorAccess() {
		return pInterfaceCommunicator;
	}
	
	public ParserRule getInterfaceCommunicatorRule() {
		return getInterfaceCommunicatorAccess().getRule();
	}
	
	//AbstractComponent SystemIndependentViewPoint::AbstractComponent:
	//	CompositeComponent | Component;
	public AbstractComponentElements getAbstractComponentAccess() {
		return pAbstractComponent;
	}
	
	public ParserRule getAbstractComponentRule() {
		return getAbstractComponentAccess().getRule();
	}
	
	//BehaviorElement SystemIndependentViewPoint::BehaviorElement:
	//	InternalAction | ExternalCall | Loop | Branch;
	public BehaviorElementElements getBehaviorElementAccess() {
		return pBehaviorElement;
	}
	
	public ParserRule getBehaviorElementRule() {
		return getBehaviorElementAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Interface SystemIndependentViewPoint::Interface:
	//	'Interface'
	//	name=EString
	//	'{'
	//	'signatures' '(' signatures+=[SystemIndependentViewPoint::Signature|EString] (","
	//	signatures+=[SystemIndependentViewPoint::Signature|EString])* ')'
	//	'}';
	public InterfaceElements getInterfaceAccess() {
		return pInterface;
	}
	
	public ParserRule getInterfaceRule() {
		return getInterfaceAccess().getRule();
	}
	
	//CompositeComponent SystemIndependentViewPoint::CompositeComponent:
	//	'CompositeComponent'
	//	name=EString
	//	'{' ('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
	//	requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
	//	'providedInterfaces' '(' providedInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
	//	providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')'
	//	'system' system=[AssemblyViewPoint::System|EString]
	//	'}';
	public CompositeComponentElements getCompositeComponentAccess() {
		return pCompositeComponent;
	}
	
	public ParserRule getCompositeComponentRule() {
		return getCompositeComponentAccess().getRule();
	}
	
	//Signature SystemIndependentViewPoint::Signature:
	//	'Signature'
	//	name=EString
	//	'{'
	//	'returnValue' returnValue=Type ('parameters' '{' parameters+=Parameter ("," parameters+=Parameter)* '}')?
	//	'}';
	public SignatureElements getSignatureAccess() {
		return pSignature;
	}
	
	public ParserRule getSignatureRule() {
		return getSignatureAccess().getRule();
	}
	
	//Component SystemIndependentViewPoint::Component:
	//	'Component'
	//	name=EString
	//	'{' ('requiredInterfaces' '(' requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
	//	requiredInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')')?
	//	'providedInterfaces' '(' providedInterfaces+=[SystemIndependentViewPoint::Interface|EString] (","
	//	providedInterfaces+=[SystemIndependentViewPoint::Interface|EString])* ')'
	//	'services' '{' services+=Service ("," services+=Service)* '}'
	//	'}';
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//enum Type returns SystemIndependentViewPoint::Type:
	//	VOID | BOOLEAN | CHAR | DATE | DOUBLE | FLOAT | LIST | INT | LONG | MAP | STRING;
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Parameter SystemIndependentViewPoint::Parameter:
	//	'Parameter'
	//	name=EString
	//	'{'
	//	'type' type=Type
	//	'}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Service SystemIndependentViewPoint::Service:
	//	'Service'
	//	'{'
	//	'signature' signature=[SystemIndependentViewPoint::Signature|EString]
	//	'behaviourDescription' behaviourDescription=BehaviourDescription
	//	'}';
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}
	
	//BehaviourDescription SystemIndependentViewPoint::BehaviourDescription:
	//	{SystemIndependentViewPoint::BehaviourDescription}
	//	'BehaviourDescription'
	//	'{' ('behaviorElements' '{' behaviorElements+=BehaviorElement ("," behaviorElements+=BehaviorElement)* '}')?
	//	'}';
	public BehaviourDescriptionElements getBehaviourDescriptionAccess() {
		return pBehaviourDescription;
	}
	
	public ParserRule getBehaviourDescriptionRule() {
		return getBehaviourDescriptionAccess().getRule();
	}
	
	//InternalAction SystemIndependentViewPoint::InternalAction:
	//	{SystemIndependentViewPoint::InternalAction}
	//	'InternalAction';
	public InternalActionElements getInternalActionAccess() {
		return pInternalAction;
	}
	
	public ParserRule getInternalActionRule() {
		return getInternalActionAccess().getRule();
	}
	
	//ExternalCall SystemIndependentViewPoint::ExternalCall:
	//	'ExternalCall'
	//	'{'
	//	'signature' signature=[SystemIndependentViewPoint::Signature|EString]
	//	'}';
	public ExternalCallElements getExternalCallAccess() {
		return pExternalCall;
	}
	
	public ParserRule getExternalCallRule() {
		return getExternalCallAccess().getRule();
	}
	
	//Loop SystemIndependentViewPoint::Loop:
	//	{SystemIndependentViewPoint::Loop}
	//	'Loop'
	//	'{' ('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
	//	behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
	//	'}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//Branch SystemIndependentViewPoint::Branch:
	//	{SystemIndependentViewPoint::Branch}
	//	'Branch'
	//	'{' ('behaviorElements' '(' behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString] (","
	//	behaviorElements+=[SystemIndependentViewPoint::BehaviorElement|EString])* ')')?
	//	'}';
	public BranchElements getBranchAccess() {
		return pBranch;
	}
	
	public ParserRule getBranchRule() {
		return getBranchAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
