/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsm.simplePalladio.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdsm.simplePalladio.SimplepalladioRuntimeModule;
import org.xtext.mdsm.simplePalladio.SimplepalladioStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SimplepalladioIdeSetup extends SimplepalladioStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SimplepalladioRuntimeModule(), new SimplepalladioIdeModule()));
	}
	
}
