/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsm.simplePalladio.ide;


/**
 * Use this class to register ide components.
 */
public class SimplepalladioIdeModule extends AbstractSimplepalladioIdeModule {
}
