<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ecore:EPackage [
<!ENTITY _0 "http://www.eclipse.org/emf/2002/Ecore">
]>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplePalladio" nsURI="http://www.example.org/simplePalladio"
    nsPrefix="simplePalladio">
  <eSubpackages name="SystemIndependentViewType" nsURI="http://www.example.org/simplePalladio/SystemIndependentViewType"
      nsPrefix="SystemIndependentViewType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="RepositoryViewType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryElements" lowerBound="1"
          upperBound="-1" eType="#//SystemIndependentViewType/AbstractRepositoryElement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//SystemIndependentViewType/AbstractRepositoryElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" lowerBound="1"
          upperBound="-1" eType="#//SystemIndependentViewType/Signature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//SystemIndependentViewType/AbstractComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="ProvidedInterfacesMustMatchWithSystemProvidedInterfaces RequiredInterfacesMustMatchWithSystemRequiredInterfaces"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="ProvidedInterfacesMustMatchWithSystemProvidedInterfaces" value="(system.providedInterfaces->includesAll(self.providedInterfaces)) and (providedInterfaces->includesAll(self.system.providedInterfaces))"/>
        <details key="RequiredInterfacesMustMatchWithSystemRequiredInterfaces" value="(system.requiredInterfaces->includesAll(self.requiredInterfaces)) and (requiredInterfaces->includesAll(self.system.requiredInterfaces))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="1"
          eType="#//AssemblyViewPoint/System"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="#//SystemIndependentViewType/AbstractRepositoryElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnValue" lowerBound="1"
          eType="#//SystemIndependentViewType/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//SystemIndependentViewType/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent" abstract="true"
        eSuperTypes="#//SystemIndependentViewType/AbstractRepositoryElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" lowerBound="1"
          upperBound="-1" eType="#//SystemIndependentViewType/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
          eType="#//SystemIndependentViewType/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//SystemIndependentViewType/AbstractComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="services" lowerBound="1"
          upperBound="-1" eType="#//SystemIndependentViewType/Service" containment="true"
          eOpposite="#//SystemIndependentViewType/Service/component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Type">
      <eLiterals name="VOID"/>
      <eLiterals name="BOOLEAN"/>
      <eLiterals name="CHAR"/>
      <eLiterals name="DATE"/>
      <eLiterals name="DOUBLE"/>
      <eLiterals name="FLOAT"/>
      <eLiterals name="LIST"/>
      <eLiterals name="INT"/>
      <eLiterals name="LONG"/>
      <eLiterals name="MAP"/>
      <eLiterals name="STRING"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="TypeMustNotBeVoid"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="TypeMustNotBeVoid" value="type &lt;> Type::VOID"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//SystemIndependentViewType/Type" defaultValueLiteral="BOOLEAN"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractRepositoryElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
          eType="#//SystemIndependentViewType/Signature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourDescription"
          lowerBound="1" eType="#//SystemIndependentViewType/BehaviourDescription"
          containment="true" eOpposite="#//SystemIndependentViewType/BehaviourDescription/service"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//SystemIndependentViewType/Component" eOpposite="#//SystemIndependentViewType/Component/services"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviourDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorElements" upperBound="-1"
          eType="#//SystemIndependentViewType/BehaviorElement" containment="true"
          eOpposite="#//SystemIndependentViewType/BehaviorElement/behaviourDescription"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
          eType="#//SystemIndependentViewType/Service" eOpposite="#//SystemIndependentViewType/Service/behaviourDescription"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//SystemIndependentViewType/BehaviorElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalCall" eSuperTypes="#//SystemIndependentViewType/BehaviorElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="MustCallRequiredInterfaces"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="MustCallRequiredInterfaces" value="self.behaviourDescription.service.component.requiredInterfaces->exists(it: Interface | it.signatures->includes(signature))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
          eType="#//SystemIndependentViewType/Signature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//SystemIndependentViewType/BehaviorElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorElements" upperBound="-1"
          eType="#//SystemIndependentViewType/BehaviorElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//SystemIndependentViewType/BehaviorElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorElements" upperBound="-1"
          eType="#//SystemIndependentViewType/BehaviorElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourDescription"
          lowerBound="1" eType="#//SystemIndependentViewType/BehaviourDescription"
          eOpposite="#//SystemIndependentViewType/BehaviourDescription/behaviorElements"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="AssemblyViewPoint" nsURI="http://www.example.org/simplePalladio/AssemblyViewPoint"
      nsPrefix="AssemblyViewPoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyViewType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="systems" lowerBound="1"
          upperBound="-1" eType="#//AssemblyViewPoint/System" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="System">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" lowerBound="1"
          upperBound="-1" eType="#//SystemIndependentViewType/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
          eType="#//SystemIndependentViewType/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemElements" lowerBound="1"
          upperBound="-1" eType="#//AssemblyViewPoint/AbstractSystemElement" containment="true"
          eOpposite="#//AssemblyViewPoint/AbstractSystemElement/system"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext" eSuperTypes="#//AssemblyViewPoint/AbstractSystemElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//SystemIndependentViewType/AbstractComponent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedRoles" lowerBound="1"
          upperBound="-1" eType="#//AssemblyViewPoint/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
          eType="#//AssemblyViewPoint/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext" eType="#//DeploymentViewPoint/AllocationContext"
          eOpposite="#//DeploymentViewPoint/AllocationContext/assembly"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//AssemblyViewPoint/AbstractSystemElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentAssemblyContext"
          lowerBound="1" eType="#//AssemblyViewPoint/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//SystemIndependentViewType/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromAssemblyConnectors"
          upperBound="-1" eType="#//AssemblyViewPoint/AssemblyConnector" eOpposite="#//AssemblyViewPoint/AssemblyConnector/requiredRole"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector" eSuperTypes="#//AssemblyViewPoint/AbstractConnector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="InterfaceMustMatch ConnectedMustBeOfSameKind"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="InterfaceMustMatch" value="role.interface = interface"/>
        <details key="ConnectedMustBeOfSameKind" value="let system : System = self.system in (system.providedInterfaces->includes(interface) and role.parentAssemblyContext.providedRoles->includes(role)) or (system.requiredInterfaces->includes(interface) and role.parentAssemblyContext.requiredRoles->includes(role))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1"
          eType="#//AssemblyViewPoint/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//SystemIndependentViewType/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector" eSuperTypes="#//AssemblyViewPoint/AbstractConnector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="AssemblyContextsMustNotMatch"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="AssemblyContextsMustNotMatch" value="providedRole.parentAssemblyContext &lt;> requiredRole.parentAssemblyContext"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
          eType="#//AssemblyViewPoint/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole" lowerBound="1"
          eType="#//AssemblyViewPoint/Role" eOpposite="#//AssemblyViewPoint/Role/fromAssemblyConnectors"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractConnector" abstract="true"
        eSuperTypes="#//AssemblyViewPoint/AbstractSystemElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractSystemElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="1"
          eType="#//AssemblyViewPoint/System" eOpposite="#//AssemblyViewPoint/System/systemElements"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="DeploymentViewPoint" nsURI="http://www.example.org/simplePalladio/DeploymentViewPoint"
      nsPrefix="DeploymentViewPoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentViewType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="environmentElements"
          lowerBound="1" upperBound="-1" eType="#//DeploymentViewPoint/AbstractEnvironmentElement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationViewType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContexts" lowerBound="1"
          upperBound="-1" eType="#//DeploymentViewPoint/AllocationContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//DeploymentViewPoint/AbstractEnvironmentElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//DeploymentViewPoint/Link" eOpposite="#//DeploymentViewPoint/Link/containers"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//DeploymentViewPoint/AbstractEnvironmentElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType &_0;#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="2"
          upperBound="-1" eType="#//DeploymentViewPoint/Container" eOpposite="#//DeploymentViewPoint/Container/links"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="ConnectedAssemblyContextsMustBeOnConnectedContainers"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="ConnectedAssemblyContextsMustBeOnConnectedContainers" value="assembly.requiredRoles->forAll(r :simplePalladio::AssemblyViewPoint::Role | r.fromAssemblyConnectors->forAll(ac : simplePalladio::AssemblyViewPoint::AssemblyConnector | ac.providedRole.parentAssemblyContext.allocationContext.container = self.container or ac.providedRole.parentAssemblyContext.allocationContext.container.links->includes(self.container)))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//DeploymentViewPoint/Container"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assembly" lowerBound="1"
          eType="#//AssemblyViewPoint/AssemblyContext" eOpposite="#//AssemblyViewPoint/AssemblyContext/allocationContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractEnvironmentElement" abstract="true"/>
  </eSubpackages>
</ecore:EPackage>
