/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AssemblyViewTypeUiModule extends AbstractAssemblyViewTypeUiModule {

	public AssemblyViewTypeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
