/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AssemblyViewTypeRuntimeModule extends AbstractAssemblyViewTypeRuntimeModule {
}
