/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdsd.simplepalladio.EnvironmentViewTypeRuntimeModule;
import org.xtext.mdsd.simplepalladio.EnvironmentViewTypeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EnvironmentViewTypeIdeSetup extends EnvironmentViewTypeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EnvironmentViewTypeRuntimeModule(), new EnvironmentViewTypeIdeModule()));
	}
	
}
