/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdsd.simplepalladio.RepositoryViewTypeRuntimeModule;
import org.xtext.mdsd.simplepalladio.RepositoryViewTypeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RepositoryViewTypeIdeSetup extends RepositoryViewTypeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RepositoryViewTypeRuntimeModule(), new RepositoryViewTypeIdeModule()));
	}
	
}
