/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mdsd.simplepalladio.repositoryviewtype.ui.internal.RepositoryviewtypeActivator;

public class RepositoryViewTypeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RepositoryviewtypeActivator.getInstance().getInjector("org.xtext.mdsd.simplepalladio.RepositoryViewType");
	}

}
