/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EnvironmentViewTypeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/mdsd/simplepalladio/parser/antlr/internal/InternalEnvironmentViewType.tokens");
	}
}
