/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsm.simplePalladio.simplepalladio;

import org.eclipse.emf.ecore.EObject;

import simplePalladio.AssemblyViewPoint.AssemblyViewType;

import simplePalladio.DeploymentViewPoint.AllocationViewType;
import simplePalladio.DeploymentViewPoint.EnvironmentViewType;

import simplePalladio.SystemIndependentViewPoint.RepositoryViewType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getRepositoryViewType <em>Repository View Type</em>}</li>
 *   <li>{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getAssemblyViewType <em>Assembly View Type</em>}</li>
 *   <li>{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getRepositoryViewType2 <em>Repository View Type2</em>}</li>
 *   <li>{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getAssemblyViewType2 <em>Assembly View Type2</em>}</li>
 *   <li>{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getEnvironmentViewType <em>Environment View Type</em>}</li>
 *   <li>{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getAllocationViewType <em>Allocation View Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Repository View Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repository View Type</em>' containment reference.
   * @see #setRepositoryViewType(RepositoryViewType)
   * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel_RepositoryViewType()
   * @model containment="true"
   * @generated
   */
  RepositoryViewType getRepositoryViewType();

  /**
   * Sets the value of the '{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getRepositoryViewType <em>Repository View Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repository View Type</em>' containment reference.
   * @see #getRepositoryViewType()
   * @generated
   */
  void setRepositoryViewType(RepositoryViewType value);

  /**
   * Returns the value of the '<em><b>Assembly View Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assembly View Type</em>' containment reference.
   * @see #setAssemblyViewType(AssemblyViewType)
   * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel_AssemblyViewType()
   * @model containment="true"
   * @generated
   */
  AssemblyViewType getAssemblyViewType();

  /**
   * Sets the value of the '{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getAssemblyViewType <em>Assembly View Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assembly View Type</em>' containment reference.
   * @see #getAssemblyViewType()
   * @generated
   */
  void setAssemblyViewType(AssemblyViewType value);

  /**
   * Returns the value of the '<em><b>Repository View Type2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repository View Type2</em>' containment reference.
   * @see #setRepositoryViewType2(RepositoryViewType)
   * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel_RepositoryViewType2()
   * @model containment="true"
   * @generated
   */
  RepositoryViewType getRepositoryViewType2();

  /**
   * Sets the value of the '{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getRepositoryViewType2 <em>Repository View Type2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repository View Type2</em>' containment reference.
   * @see #getRepositoryViewType2()
   * @generated
   */
  void setRepositoryViewType2(RepositoryViewType value);

  /**
   * Returns the value of the '<em><b>Assembly View Type2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assembly View Type2</em>' containment reference.
   * @see #setAssemblyViewType2(AssemblyViewType)
   * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel_AssemblyViewType2()
   * @model containment="true"
   * @generated
   */
  AssemblyViewType getAssemblyViewType2();

  /**
   * Sets the value of the '{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getAssemblyViewType2 <em>Assembly View Type2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assembly View Type2</em>' containment reference.
   * @see #getAssemblyViewType2()
   * @generated
   */
  void setAssemblyViewType2(AssemblyViewType value);

  /**
   * Returns the value of the '<em><b>Environment View Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment View Type</em>' containment reference.
   * @see #setEnvironmentViewType(EnvironmentViewType)
   * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel_EnvironmentViewType()
   * @model containment="true"
   * @generated
   */
  EnvironmentViewType getEnvironmentViewType();

  /**
   * Sets the value of the '{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getEnvironmentViewType <em>Environment View Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Environment View Type</em>' containment reference.
   * @see #getEnvironmentViewType()
   * @generated
   */
  void setEnvironmentViewType(EnvironmentViewType value);

  /**
   * Returns the value of the '<em><b>Allocation View Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocation View Type</em>' containment reference.
   * @see #setAllocationViewType(AllocationViewType)
   * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage#getModel_AllocationViewType()
   * @model containment="true"
   * @generated
   */
  AllocationViewType getAllocationViewType();

  /**
   * Sets the value of the '{@link org.xtext.mdsm.simplePalladio.simplepalladio.Model#getAllocationViewType <em>Allocation View Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allocation View Type</em>' containment reference.
   * @see #getAllocationViewType()
   * @generated
   */
  void setAllocationViewType(AllocationViewType value);

} // Model
