/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsm.simplePalladio.simplepalladio;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.mdsm.simplePalladio.simplepalladio.SimplepalladioPackage
 * @generated
 */
public interface SimplepalladioFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimplepalladioFactory eINSTANCE = org.xtext.mdsm.simplePalladio.simplepalladio.impl.SimplepalladioFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SimplepalladioPackage getSimplepalladioPackage();

} //SimplepalladioFactory
