/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mdsd.simplepalladio.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEnvironmentViewTypeScopeProvider extends DelegatingScopeProvider {
}
